version: '3.8'
services:
  research:
    image: ghcr.io/rferrali/academic-docker:latest
    volumes:
      - .:/workspaces/project
      - devcontainer-renv-cache:/renv/cache
    environment:
      - RENV_PATHS_CACHE=/renv/cache
    stdin_open: true
    tty: true

volumes:
  devcontainer-renv-cache:
